# -*- coding: utf-8 -*-
"""Rinomina feature in italiano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LijIy74cMg9gHKAvpVH17pGmAwo-NmTy
"""

import pandas as pd
from google.colab import files

# 📂 Upload CSV
uploaded = files.upload()
input_file = list(uploaded.keys())[0]

# 📊 Leggi file
df = pd.read_csv(input_file)

# 📘 Dizionario colonne (inglese → italiano)
mapping_colonne = {
    "edition": "Edizione",
    "edition_id": "ID edizione",
    "year": "Anno",
    "country": "Paese",
    "country_noc": "Codice paese (NOC)",
    "gold": "Medaglie d'oro",
    "silver": "Medaglie d'argento",
    "bronze": "Medaglie di bronzo",
    "total": "Totale medaglie",
    "paese_olimpiade": "Paese ospitante",
    "citta_olimpiade": "Città ospitante",

    "AG.LND.PRCP.MM": "Precipitazioni (mm)",
    "AG.SRF.TOTL.K2": "Superficie totale (km²)",
    "BX.KLT.DINV.WD.GD.ZS": "Investimenti diretti esteri (% PIL)",
    "EN.POP.DNST": "Densità di popolazione",
    "FP.CPI.TOTL.ZG": "Inflazione (%)",
    "MS.MIL.XPND.CN": "Spesa militare",
    "MS.MIL.XPND.GD.ZS": "Spesa militare (% PIL)",
    "NE.CON.GOVT.CD": "Consumi governo",
    "NE.DAB.TOTL.CN": "Debito totale",
    "NE.TRD.GNFS.ZS": "Commercio (% PIL)"
}

# 📝 Rinomina le colonne del DataFrame
df = df.rename(columns=mapping_colonne)

# Mostra le prime righe del DataFrame con le colonne rinominate
display(df.head())

# 💾 Salva il DataFrame tradotto in un nuovo file CSV
output_filename = 'dataset_olimpiadi_indicatori_ita.csv'
df.to_csv(output_filename, index=False, encoding='utf-8')

print(f"DataFrame salvato con successo in '{output_filename}'")